modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Random%20Mob%20Effects"
logoFile="icon.png"

[[mods]]
modId="randommobeffects"
version="3.2"
displayName="Random Mob Effects"
displayURL="https://curseforge.com/minecraft/mc-mods/random-mob-effects"
authors="Rick South"
description='''Randomly assigns a potion effect to all hostile mobs in the world. With blacklist and modded effects supported.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.randommobeffects]]
    modId="collective"
    mandatory=true
    versionRange="[7.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.randommobeffects]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"