modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Softer%20Hay%20Bales"
logoFile="icon.png"

[[mods]]
modId="softerhaybales"
version="3.1"
displayName="Softer Hay Bales"
displayURL="https://curseforge.com/minecraft/mc-mods/softer-hay-bales"
authors="Rick South"
description='''Makes hay bales negate fall damage entirely, Assassin's Creed style.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.softerhaybales]]
    modId="collective"
    mandatory=true
    versionRange="[7.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.softerhaybales]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.2]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "softerhaybales_neoforge.mixins.json"