modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Shulker%20Drops%20Two"
logoFile="icon.png"

[[mods]]
modId="shulkerdropstwo"
version="3.2"
displayName="Shulker Drops Two"
displayURL="https://curseforge.com/minecraft/mc-mods/shulker-drops-two"
authors="Rick South"
description='''A minimalistic configurable mod that allows shulkers to drop two or more shells and ignore their default drop chance.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.shulkerdropstwo]]
    modId="collective"
    mandatory=true
    versionRange="[7.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.shulkerdropstwo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.2]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "shulkerdropstwo_neoforge.mixins.json"