modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Scaffolding%20Drops%20Nearby"
logoFile="icon.png"

[[mods]]
modId="scaffoldingdropsnearby"
version="3.1"
displayName="Scaffolding Drops Nearby"
displayURL="https://curseforge.com/minecraft/mc-mods/scaffolding-drops-nearby"
authors="Rick South"
description='''When breaking a scaffolding block, all chained blocks will drop at the first block's position.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.scaffoldingdropsnearby]]
    modId="collective"
    mandatory=true
    versionRange="[7.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.scaffoldingdropsnearby]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.2]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "scaffoldingdropsnearby_neoforge.mixins.json"