modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Current%20Game%20Music%20Track"
logoFile="icon.png"

[[mods]]
modId="currentgamemusictrack"
version="1.0"
displayName="Current Game Music Track"
displayURL="https://curseforge.com/minecraft/mc-mods/current-game-music-track"
authors="Rick South"
description='''Shows the title of the game music track that's currently playing when it starts in the GUI.
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.currentgamemusictrack]]
    modId="collective"
    mandatory=true
    versionRange="[6.80,)"
    ordering="NONE"
    side="BOTH"