modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Flower%20Mimics"
logoFile="icon.png"

[[mods]]
modId="flowermimics"
version="1.3"
displayName="Flower Mimics"
displayURL="https://curseforge.com/minecraft/mc-mods/flower-mimics"
authors="Rick South"
description='''SpookyJam 2023: Be careful around flowers at night.. they might transform into monsters!
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.flowermimics]]
    modId="collective"
    mandatory=true
    versionRange="[7.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.flowermimics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"